/*
  DROPS ALL TABLES USED FOR TESTING PURPOSES
*/

BEGIN TRANSACTION;

DROP TABLE IF EXISTS ANIMALS;
DROP TABLE IF EXISTS PHYSICAL_ATTRIBUTES;
DROP TABLE IF EXISTS ANIMAL_CHARACTERISTICS;

END TRANSACTION;
