/*
  QUERY THAT JOINS THE ANIMALS TABLE TO THE PHYSICAL_ATTRIBUTES TABLE
  THIS RESULTING QUERY IS ALL THAT IS REQUIRED OF US FOR DELIVERABLE 1
  IT WILL RETURN A TABLE WITH ALL ANIMAL NAMES + THEIR SPECIFIC PHYSICAL PHYSICAL_ATTRIBUTES
  WHAT NEEDS TO BE DONE IS TO INCORPORATE THIS INTO OUR C++ PROGRAM AND MAKE IT VIEWABLE USING THE QTFRAMEWORK
*/

SELECT animal_id,
       NAME,
       gender,
       age,
       species,
       breed,
       hair_type,
       hair_colour
FROM   ANIMALS
       INNER JOIN PHYSICAL_ATTRIBUTES
               ON ANIMALS.animal_id = PHYSICAL_ATTRIBUTES.a_id;
